global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "catalog"
    static_configs:
      - targets: ["catalog:3001"]
    metrics_path: /metrics

  - job_name: "identity"
    static_configs:
      - targets: ["identity:3002"]
    metrics_path: /metrics

  - job_name: "basket"
    static_configs:
      - targets: ["basket:3003"]
    metrics_path: /metrics

  - job_name: "ordering"
    static_configs:
      - targets: ["ordering:3004"]
    metrics_path: /metrics

  - job_name: "webhooks"
    static_configs:
      - targets: ["webhooks:3005"]
    metrics_path: /metrics

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:3000"]
    metrics_path: /metrics
